import Head from 'next/head'
// import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import { useState } from 'react'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'
import Awards from '../../components/Awards'
import Banner from '../../components/Banner'
import Brands from '../../components/Brands'
import { Featured } from '../../components/Featured'
import Slider from '../../components/Slider'
import Footer from '../../components/Footer'
import { useInView } from 'react-intersection-observer';
import News from '../../components/News'

// const myFont = localFont({ src: './Fonts/SctoGroteskABold.woff2' })

const Grotesk = localFont({
  src: [
    {
      path: './Fonts/SctoGroteskA-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './Fonts/SctoGroteskA-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './Fonts/SctoGroteskA-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
})


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [bgColor, setBgColor] = useState('#f4f4f4')
  const [fontColor, setfontColor] = useState('#252422')
  // #252422-#f4f4f4
  // #f9cdcd-#252422

  const [showNavbar, setShowNavbar] = useState(true)

  // const [sliderOn, setSliderOn] = useState(false)

  const [ref, inView] = useInView({
    threshold: 0.30,    // Trigger when visible percentage is 40% or more
  });

  // useEffect(() => {
  //   if (inView)setSliderOn(true)
  //   if (!inView)setSliderOn(false)
  // }, [inView])


  // const [SliderOnView, setFootView] = useState(false)

  // useEffect(() => {
  //   setTimeout(() => {
  //     setBgColor('#f4f4f4')
  //     setfontColor('#000')
  //   }, 2000);
  // }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* i added blur to the whole page for a bit of smoothness in the looks */}
      {/* style={{ backgroundColor: bgColor, color: fontColor }} */}


      <main className={`noise duration-[650ms] ease-in-out relative blur-[0.1px] md:blur-[0.3px] ${inView ? 'bg-[#252422] text-[#f9cdcd]' : 'bg-[#f4f4f4] text-[#252422]'}`}   >
        <div className={Grotesk.className} >

          <Navbar showNavbar />
          <Hero />
          <Awards />
          <Banner />
          <Brands />

          <Featured inView={inView} />

          <div ref={ref}>
            <Slider inView={inView} />
          </div>
          <News inView={inView}/>
          <Footer/>
          {/* <div className='h-[5000px]'></div> */}

        </div>

      </main>



      {/* <Footer /> */}
    </>
  )
}
